version: '3'

services:
  openport:
    image: jandebleser/openport
    networks:
      - no-internet
    volumes:
      - ..:/apps/openport
    command: python openport/apps/openport_app.py 22 --proxy=socks5://proxy-no-pass:1080
    environment:
      - PYTHONPATH=.
    depends_on:
      - proxy-no-pass

  openport-go:
    image: openport-client-go
    networks:
      - no-internet
    command: ./openport 22 --proxy=socks5h://proxy-no-pass:1080 --verbose
    # command: curl --socks5 socks5h://proxy-no-pass:1080 http://ifcfg.co
    depends_on:
      - proxy-no-pass

  proxy-no-pass:
    image: serjs/go-socks5-proxy
    networks:
      - no-internet
      - internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
