
name: openport
version: '1.1.0'
summary: Open a port from your device to the internet.
description: |
  Forward a port from your device to the internet. Manage
  and monitor your home pc from work, or keep track of your 
  army of IoT toys.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  openport:
    plugin: python
      source: https://github.com/jandebleser/openport.git
